In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install panda


In [3]:
a = np.arange(1, 11)
b = np.arange(1, 11)

print(a + b)
print(np.add(a, b))

print(a - b)
print(np.subtract(a, b))

print(a*b)
print(np.multiply(a, b))

print(a/b)
print(np.divide(a, b))


[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
a = np.arange(1, 11)
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))




[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [5]:
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
s


0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

In [6]:
s = pd.Series([98, 89, 95], index=['A', 'B', 'C'])
s

A    98
B    89
C    95
dtype: int64

In [7]:
arr = np.arange(12.).reshape(4, 3)
print(arr)
print('\n')
df = pd.DataFrame(pd.DataFrame(arr))
print(df)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


     0     1     2
0  0.0   1.0   2.0
1  3.0   4.0   5.0
2  6.0   7.0   8.0
3  9.0  10.0  11.0


In [8]:
df = pd.read_csv('countries.csv') 
df
df2 = pd.read_csv('weather.csv', encoding='euc-kr')
df2

df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5 non-null      object
 1   country     5 non-null      object
 2   area        5 non-null      int64 
 3   capital     5 non-null      object
 4   population  5 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes


In [23]:
df.columns
df.capital


0         Seoul
1    Washington
2         Tokyo
3       Beijing
4        Moscow
Name: capital, dtype: object

In [30]:
df2.columns


Index(['일시', '평균기온', '최대풍속', '평균풍속'], dtype='object')

In [25]:
df.iloc[0]

Unnamed: 0          KR
country          Korea
area             98480
capital          Seoul
population    51780579
Name: 0, dtype: object

In [26]:
w = df.capital == 'Seoul'

df[w]

,Unnamed: 0,country,area,capital,population
0,KR,Korea,98480,Seoul,51780579


In [34]:
col1 = df2[['일시']]
col2 = df2[['평균기온']]

merged = pd.concat([col1, col2], axis=1)
print(merged)

              일시  평균기온
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]
